Check enrichment numeric
abbvie-external/OmicNavigator pull request #14
Opened 2023-05-23 10:50 UTC by curadomr

Provides checks if 'nominal' and 'adjusted' columns for Enrichment tables are numeric. Also includes checks in tinytest file (testCheck.R)

2023-05-23 19:29 UTC, jdblischak requested changes
Code looks good and the tests pass. Is the plan to [create a new release](https://github.com/abbvie-external/OmicNavigator/blob/main/CONTRIBUTING.md#tag-a-new-release) immediately? Or can this wait until the next release of the web app (which will automatically create a new R package release)?

To do:

* Bump the version. For immediate release, bump to 1.13.10. Otherwise use a dev version, 1.13.9.1
* Add a bullet to `NEWS.md`. For immediate release, also manually add the header `# 1.13.10`. Otherwise don't include a header

2023-05-24 21:03 UTC, bengalengel commented
let's do an immediate release please!

2023-05-27 00:22 UTC, jdblischak approved these changes

2023-05-27 00:25 UTC, jdblischak commented
I can't merge since I don't have write access. For an immediate release, I recommend the following steps:

1. Squash and merge this PR (ie combine all the commits into a single commit with an informative message)
2. In your terminal, pull the latest changes `git pull upstream main`
3. Follow the remaining instructions to [tag a new release](https://github.com/abbvie-external/OmicNavigator/blob/main/CONTRIBUTING.md#tag-a-new-release), starting with the step to `git tag -a v1.13.10 -m "v1.13.10"`

2023-06-07 20:13 UTC, merged